version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ".env.development"
    environment:
      - DB_HOST=host.docker.internal
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ".env.development"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
